=== Krasilnikov-Ilya/XmlJson_Practice/Решения Красильников/Krasilnikov.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Passport">
        <xs:complexType>
            <!-- Я бы наделал составных, но сложнее - не всегда лучше -->
            <xs:sequence>
                <!-- Серия и номер одним элементом, проще искать -->
                <xs:element name="SerNum" type="xs:decimal" maxOccurs="1"/>
                <!-- Моё видение передачи ФИО, только простые элементы -->
                <xs:element name="last_name" type="xs:string" maxOccurs="1"/>
                <xs:element name="first_name" type="xs:string" maxOccurs="1"/>
                <xs:element name="patronymic" type="xs:string" maxOccurs="1"/>
                <!-- Здесь будет "Оглы" для азербайджанцев, не обязательно -->
                <xs:element name="patronymictype" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <!-- Хотел сделать Boolean, но не стал :D -->
                <xs:element name="gender" type="xs:string" maxOccurs="1"/>
                <!-- Элементы дат стандартизованы -->
                <xs:element name="birthdate" type="xs:date" maxOccurs="1"/>
                <!-- Сначала тип населённого пункта (посёлок, деревня или город) -->
                <xs:element name="locality" type="xs:string" maxOccurs="1"/>
                <!-- Потом имя населённого пункта -->
                <xs:element name="locname" type="xs:string" maxOccurs="1"/>
                <!-- Кем выдан -->
                <xs:element name="issuedby" type="xs:string" maxOccurs="1"/>
                <!-- Дата выдачи -->
                <xs:element name="issuedate" type="xs:date" maxOccurs="1"/>
                <!-- Код подразделения имел дефис, но работаем только с цифрами -->
                <xs:element name="issuedbycode" type="xs:decimal" maxOccurs="1"/>
                <!-- Всё-таки добавлю один Boolean, предположим, надо знать, состоит ли в браке -->
                <xs:element name="married" type="xs:boolean" maxOccurs="1"/>
                <!-- Ещё дату и время получения данных передать надо, по гринвичу. А то вдруг женюсь -->
                <xs:element name="updated" type="xs:dateTime" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Krasilnikov-Ilya/XmlJson_Practice/Решения Красильников/Krasilnikov.xml
<?xml version="1.0" encoding="UTF-8"?>
<Passport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="Krasilnikov.xsd">
    <SerNum>1234567</SerNum>
    <last_name>Красильников</last_name>
    <first_name>Илья</first_name>
    <patronymic>Азатович</patronymic>
    <!-- Здесь могло быть "Оглы" -->
    <gender>Male</gender>
    <birthdate>1993-11-01</birthdate>
    <locality>гор.</locality>
    <locname>Ижевск</locname>
    <issuedby>Отделом отдела отделов по отдеду в отделе</issuedby>
    <issuedate>2000-01-01</issuedate>
    <issuedbycode>123456</issuedbycode>
    <married>0</married>
    <updated>2022-05-12T10:00:00.0</updated>
</Passport>
