=== Krasilnikov-Ilya/XmlJson_Practice/Анастасия Черепенина ++/Passport(XSD).xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:element name="passportdata">
             <xs:complexType>
			    <xs:sequence>
				     <xs:element name="series" type="xs:integer"/>
					 <xs:element name="number" type="xs:integer"/>
					 <xs:element name="surname" type="xs:string"/>
                     <xs:element name="name" type="xs:string"/>
                     <xs:element name="patronymic" type="xs:string"/>
                     <xs:element name="gender" type="xs:string"/>
                     <xs:element name="birthday" type="xs:date"/>
					 <xs:element name="locality" type="xs:string"/>
					 <xs:element name="city_name" type="xs:string"/>
					 <xs:element name="issued_by" type="xs:string"/>
					 <xs:element name="day_of_issue" type="xs:gDay"/>
					 <xs:element name="month_of_issue" type="xs:gMonth"/>
					 <xs:element name="year_of_issue" type="xs:gYear"/>
					 <xs:element name="current_date" type="xs:dateTime"/>
					 <xs:element name="start" type="xs:time"/>
				</xs:sequence>
			 </xs:complexType>
   </xs:element>
</xs:schema>

=== Krasilnikov-Ilya/XmlJson_Practice/Анастасия Черепенина ++/Passport(Xml).xml
<?xml version="1.0" encoding="UTF-8"?>
<passportdata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="Passport(XSD).xsd">
      <series>1234</series>
      <number>567890</number>
      <surname>Cherepenina</surname>
      <name>Anastasia</name>
	  <patronymic>Romanovna </patronymic>
	  <gender>female</gender>
	  <birthday>1997-07-28 </birthday>
	  <locality>city</locality>
	  <city_name>Moscow</city_name>
	  <issued_by>department of departments </issued_by>
	  <day_of_issue>---15</day_of_issue>
	  <month_of_issue>--12</month_of_issue>
	  <year_of_issue>2017</year_of_issue>
	  <current_date>2022-05-15T22:06:55</current_date>
	  <start>22:06:55+03:00</start>
</passportdata>
