=== Krasilnikov-Ilya/XmlJson_Practice/Яковенко Станислав ++/output.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="сustomer_data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="document">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:choice  maxOccurs="unbounded">
                                <xs:element type="xs:string" name="document_type"/>
                                <xs:element name="series" type="xs:integer"/>
                                <xs:element name="number" type="xs:integer"/>
                                <xs:element name="first_name">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:maxLength value="20"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>
                                <xs:element name="patronymic">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:maxLength value="20"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>
                                <xs:element name="surname">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:maxLength value="20"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>
                                <xs:element type="xs:date" name="birth_date"/>
                                <xs:element type="xs:string" name="gender"/>
                                <xs:element type="xs:string" name="division_code"/>
                                <xs:element type="xs:string" name="issued_by"/>
                                <xs:element type="xs:date" name="issue_date"/>
                                <xs:element name="birth_place">
                                 <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                   <xs:maxLength value="100"/>
                                  </xs:restriction>
                                 </xs:simpleType>
                                </xs:element>
                                <xs:element name="registration">
                                 <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                   <xs:maxLength value="100"/>
                                  </xs:restriction>
                                </xs:simpleType>
                               </xs:element>
                            </xs:choice>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Krasilnikov-Ilya/XmlJson_Practice/Яковенко Станислав ++/паспорт Яковенко.xml
<?xml version="1.0" encoding="utf-8"?>
<сustomer_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="output.xsd">
 <document>
  <document_type>Паспорт РФ</document_type>
   <series>0101</series>
   <number>454849</number>
   <first_name>Иван</first_name>
   <patronymic>Николавевич</patronymic>
   <surname>Сидоров</surname>
   <birth_date>1995-01-20</birth_date>
   <gender>МУЖ</gender>
   <division_code>770-010</division_code>
   <issued_by>Отделом УФМС России по гор.Москве</issued_by>
   <issue_date>2015-05-05</issue_date>
   <birth_place>Россия,г.Москва</birth_place>
   <registration>г.Москва,ул.Ленина 25, кв.5</registration>
</document>
</сustomer_data>
