=== Krasilnikov-Ilya/XmlJson_Practice/Юлия Макарова ++/passport_data.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
     <xs:element name="passport_data">
          <xs:complexType>
            <xs:sequence>
                <xs:element name="series" type="xs:string"/>
                <xs:element name="number" type="xs:positiveInteger"/>
                <xs:element name="surname" type="xs:string"/>
                <xs:element name="first_name" type="xs:string"/>
                <xs:element name="patronymic" type="xs:string"/> 
                <xs:element name="gender" type="xs:string"/>
                <xs:element name="birth_date" type="xs:date"/>
                <xs:element name="locality_type" type="xs:string"/>
                <xs:element name="locality_name" type="xs:string"/>
                <xs:element name="issued_by" type="xs:string"/>
                <xs:element name="issue_date" type="xs:date"/>
                <xs:element name="division_code" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
      </xs:element>
</xs:schema>

=== Krasilnikov-Ilya/XmlJson_Practice/Юлия Макарова ++/passport_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<passport_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="passport_data.xsd">
	<series>1234</series>
	<number>567890</number>
	<surname>Макарова</surname>
	<first_name>Юлия</first_name>
	<patronymic>Альбертовна</patronymic>
	<gender>жен</gender>
	<birth_date>2000-12-30</birth_date>
	<locality_type>Город</locality_type>
	<locality_name>Самара</locality_name>
	<issued_by>Отделом УФМС РФ по Самарской области</issued_by>
	<issue_date>2019-01-12</issue_date>
	<division_code>180-001</division_code>
</passport_data>
