=== Krasilnikov-Ilya/XmlJson_Practice/Константин Александров ++/passport.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="passport">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="fildes" type="passportFildes" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="passportFildes">
		<xs:sequence>
			<xs:element name = "document_type" type = "xs:string"/>
			<xs:element name = "series" type = "xs:integer"/>
			<xs:element name = "number" type = "xs:integer"/>
			<xs:element name = "issued_by" type = "xs:string"/>
			<xs:element name = "issue_date" type = "xs:date"/>
			<xs:element name = "division_code" type = "xs:string"/>
			<xs:element name = "surname" type = "xs:string"/>
			<xs:element name = "first_name" type = "xs:string"/>
			<xs:element name = "patronymic" type = "xs:string"/>
			<xs:element name = "birth_date" type = "xs:date"/>
			<xs:element name = "gender" type = "xs:string"/>
			<xs:element name = "birth_place" type = "xs:string"/>
			<xs:element name = "registration" type = "xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Krasilnikov-Ilya/XmlJson_Practice/Константин Александров ++/passport.xml
<?xml version="1.0" encoding="UTF-8"?>
<passport xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="passport.xsd">
	<fildes>	
		<document_type>Паспорт РФ</document_type>
		<series>5678</series>
		<number>673458</number>
		<issued_by>Отделом УФМС РФ по Самарской области</issued_by>
		<issue_date>2012-01-13</issue_date>
		<division_code>630-324</division_code>
		<surname>Александров</surname>
		<first_name>Константин</first_name>
		<patronymic>Владимирович</patronymic>
		<birth_date>1970-01-01</birth_date>
		<gender>МУЖ</gender>
		<birth_place>г. Москва</birth_place>
		<registration>г. Москва, Тверская ул., 1, кв. 1</registration>
	</fildes>
</passport>
