=== Krasilnikov-Ilya/XmlJson_Practice/Лугинин Анатолий +/LugininXSD1.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="document">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="passport" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="firstPage">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:short" name="series"/>
										<xs:element type="xs:positiveInteger" name="number"/>
										<xs:element type="xs:string" name="passportGivenBy"/>
										<xs:element type="xs:date" name="dateOfIssue"/>
										<xs:element type="xs:string" name="divisionCode"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="secondPage">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="surname"/>
										<xs:element type="xs:string" name="name"/>
										<xs:element type="xs:string" name="patronymic"/>
										<xs:element type="xs:string" name="gender"/>
										<xs:element type="xs:date" name="birthday"/>
										<xs:element type="xs:string" name="PlaceOfBirth"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="fourthPage">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="region"/>
										<xs:element type="xs:string" name="City"/>
										<xs:element type="xs:string" name="Street"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Krasilnikov-Ilya/XmlJson_Practice/Лугинин Анатолий ++/LugininXML1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:noNamespaceSchemaLocation="LugininXSD1.xsd">
	<passport>
		<firstPage>
			<series>1234</series>
			<number>141027</number>
			<passportGivenBy>ГУ МВД по городу Москва</passportGivenBy>
			<dateOfIssue>2022-05-16</dateOfIssue>
			<divisionCode>111-222</divisionCode>
		</firstPage>
		<secondPage>
			<surname>Лугинин</surname>
			<name>Анатолий</name>
			<patronymic>Алексеевич</patronymic>
			<gender>male</gender>
			<birthday>1998-10-19</birthday>
			<PlaceOfBirth>гор. Москва</PlaceOfBirth>
		</secondPage>
		<fourthPage>
			<region>Москва</region>
			<City>Москва</City>
			<Street>Пушкина,д.1,кв.1</Street>
		</fourthPage>
	</passport>
</document>
