=== Krasilnikov-Ilya/XmlJson_Practice/Плешивцева Алёна ++/test.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="clients_inf">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="type" type="xs:string"/>
                <xs:element name="pdata">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="first_name" type="xs:string"/>
                            <xs:element name="surname" type="xs:string"/>
                            <xs:element name="contacts">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="phone" type="xs:integer"/>
                                        <xs:element name="e-mail" type="xs:string"/>
                                        <xs:element name="skype" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="documents">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="document" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:choice minOccurs="0" maxOccurs="unbounded">
                                                    <xs:element name="document_type" type="xs:string"/>
                                                    <xs:element name="series" type="xs:string"/>
                                                    <xs:element name="number" type="xs:positiveInteger"/>
                                                    <xs:element name="issued_by" type="xs:string"/>
                                                    <xs:element name="issue_date" type="xs:date"/>
                                                    <xs:element name="birth_date" type="xs:date"/>
                                                    <xs:element name="gender" type="xs:string"/>
                                                    <xs:element name="birth_place" type="xs:string"/>
                                                    <xs:element name="today" type="xs:dateTime"/>
                                                    <xs:element name="time" type="xs:time"/>
                                                    <xs:element name="timezone" type="xs:time"/>
                                                </xs:choice>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Krasilnikov-Ilya/XmlJson_Practice/Плешивцева Алёна ++/result.xml
<?xml version="1.0" encoding="UTF-8"?>

<clients_inf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="test.xsd">
    <type>vip-клиент</type>
    <pdata>
        <first_name>Алена</first_name>
        <surname>Плешивцева</surname>
        <contacts>
            <phone>89164880833</phone>
            <e-mail>alenkaalex@rambler.ru</e-mail>
            <skype>alenkaalex</skype>
        </contacts>
        <documents>
            <document>
                <document_type>Паспорт РФ</document_type>
                <series>4516</series>
                <number>782404</number>
                <issued_by>УФМС России по гор.Москве по району Нижегородский</issued_by>
                <issue_date>2016-10-11</issue_date>
                <birth_date>1996-09-27</birth_date>
                <gender>Женский</gender>
                <birth_place>Москва</birth_place>
                <today>2020-05-13T15:00:00</today>
                <time>15:00:00</time>
                <timezone>00:00:00+03:00</timezone>
            </document>
        </documents>
    </pdata>
</clients_inf>
