=== Krasilnikov-Ilya/XmlJson_Practice/Lena Teteryukova ++/clients_cards.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="clients_cards">
		<xs:complexType>
		<xs:sequence>
	<xs:element name="client">
		<xs:complexType>
		<xs:sequence>
	<xs:element name="id">
	 <xs:simpleType>
	 <xs:restriction base="xs:string">
		<xs:length value="10"/>
	</xs:restriction>
	</xs:simpleType>
	</xs:element>
	<xs:element name="first_name" type="xs:string"/>
	<xs:element name="surname" type="xs:string"/>
	<xs:element name="middle_name" type="xs:string"/>
	<xs:element name="birth_date" type="xs:date"/>
		</xs:sequence>
		</xs:complexType>
		</xs:element>
	<xs:element name="cards">
		<xs:complexType>
		<xs:sequence>
	<xs:element name="card" maxOccurs="unbounded">
		<xs:complexType>
		<xs:choice minOccurs="0" maxOccurs="unbounded">
	<xs:element name="id" type="xs:positiveInteger"/>
	<xs:element name="number">
	<xs:simpleType>
	<xs:restriction base="xs:string">
         <xs:minLength value="8"/>
         <xs:maxLength value="19"/>
		</xs:restriction>
		</xs:simpleType>
		</xs:element>
	<xs:element name="type">
	<xs:simpleType>
	<xs:restriction base="xs:string">
         <xs:pattern value="debit|credit"/>
		</xs:restriction>
		</xs:simpleType>
		</xs:element>
	<xs:element name="limit">
	<xs:simpleType>
	<xs:restriction base="xs:integer">
		<xs:maxInclusive value="1000000"/>
		</xs:restriction>
		</xs:simpleType>
		</xs:element>
	<xs:element name="start_date" type="xs:date"/>
	<xs:element name="expire_date" type="xs:date"/>
			</xs:choice>
		    </xs:complexType>
		    </xs:element>
	</xs:sequence>
	</xs:complexType>
	</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>							
</xs:schema>

=== Krasilnikov-Ilya/XmlJson_Practice/Lena Teteryukova ++/clients_cards.xml
<?xml version="1.0" encoding="UTF-8"?>
<clients_cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="clients_cards.xsd">
	<client>
		<id>3524186479</id>
		<first_name>Artem</first_name>
		<surname>Ivanov</surname>
		<middle_name>Aleksandrovich</middle_name>
		<birth_date>1975-05-13</birth_date>
	</client>
	<cards>
		<card>
			<id>38976</id>
			<number>5432730013986390</number>
			<type>debit</type>
			<limit>350000</limit>
			<start_date>2020-08-12</start_date>
			<expire_date>2030-08-12</expire_date>
		</card>
		<card>
		<id>65748</id>
			<number>4432456734529076</number>
			<type>credit</type>
			<limit>1000000</limit>
			<start_date>2021-10-17</start_date>
			<expire_date>2026-10-17</expire_date>
		</card>
	</cards>
</clients_cards>
