=== Krasilnikov-Ilya/XmlJson_Practice/Nazarova Yulia ++/passport.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="homework">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="passport">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="series" type="xs:string"/>
							<xs:element name="number" type="xs:positiveInteger"/>
							<xs:element name="surname" type="xs:string"/>
							<xs:element name="first_name" type="xs:string"/>
							<xs:element name="second_name" type="xs:string"/>
							<xs:element name="gender" type="xs:string"/>
							<xs:element name="birth_date" type="xs:date"/>
							<xs:element name="region" type="xs:string"/>
							<xs:element name="birth_place" type="xs:string"/>
							<xs:element name="issued_by" type="xs:string"/>
							<xs:element name="issue_date" type="xs:date"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="date_time">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="current_date_time" type="xs:dateTime"/>
							<xs:element name="current_time" type="xs:time"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Krasilnikov-Ilya/XmlJson_Practice/Nazarova Yulia ++/passport.xml
<?xml version="1.0" encoding="UTF-8"?>
<homework xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="passport.xsd">
	<passport>
		<series>1234</series>
		<number>567890</number>
		<surname>Назарова</surname>
		<first_name>Юлия</first_name>
		<second_name>Яковлевна</second_name>
		<gender>Жен</gender>
		<birth_date>1990-01-01</birth_date>
		<region>Город</region>
		<birth_place>Москва</birth_place>
		<issued_by>Отделом УФМС РФ</issued_by>
		<issue_date>2000-01-11</issue_date>
	</passport>

	<date_time>
		<current_date_time>2022-05-15T10:30:30</current_date_time>
		<current_time>10:30:30+04:00</current_time>
	</date_time>
</homework>
