=== Krasilnikov-Ilya/XmlJson_Practice/Olga Karpova ++/Passport.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="clients_inf">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pdata">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="documents">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="document" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:choice maxOccurs="unbounded" minOccurs="0">
                                                    <xs:element type="xs:string" name="document_type"/>
                                                    <xs:element name="series">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:integer">
                                                                <xs:pattern value="[0-9][0-9][0-9][0-9]"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="pasportnumber">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:integer">
                                                                <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9]"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="insurancenumber">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="\d{3}-\d{3}-\d{3} \d{2}"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element type="xs:string" name="issued_by"/>
                                                    <xs:element type="xs:string" name="issue_date"/>
                                                    <xs:element type="xs:string" name="division_code"/>
                                                    <xs:element type="xs:string" name="first_name"/>
                                                    <xs:element type="xs:string" name="surname"/>
                                                    <xs:element name="birth_date">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="\d{2}.\d{2}.\d{4}"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="gender">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="МУЖ|ЖЕН"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element type="xs:string" name="birth_place"/>
                                                    <xs:element type="xs:dateTime" name="startdate"/>
                                                    <xs:element type="xs:time" name="start"/>
                                                    <xs:element type="xs:string" name="full_name"/>
                                                </xs:choice>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Krasilnikov-Ilya/XmlJson_Practice/Olga Karpova ++/Passport.xml
<?xml version="1.0" encoding="UTF-8"?>
<clients_inf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Passport.xsd">
    <pdata>
        <documents>
            <document>
                <document_type>Паспорт</document_type>
                <series>6800</series>
                <pasportnumber>458235</pasportnumber>
                <issued_by>2 отделом милиции люберецкого УВД московской области</issued_by>
                <issue_date>10.10.2017</issue_date>
                <division_code>725-475</division_code>
                <first_name>Ольга</first_name>
                <surname>Карпова</surname>
                <birth_date>16.07.1983</birth_date>
                <gender>ЖЕН</gender>
                <birth_place>г.Москва</birth_place>
                <startdate>2022-05-13T18:30:10.5</startdate>
                <start>18:30:10Z</start>
            </document>
            <document>
                <document_type>Страховое свидетельство</document_type>
                <insurancenumber>204-882-774 85</insurancenumber>
                <full_name>Карпова Ольга Юрьевна</full_name>
                <birth_date>16.07.1983</birth_date>
                <birth_place>г.Москва</birth_place>
                <gender>ЖЕН</gender>
            </document>
        </documents>
    </pdata>
</clients_inf>
