=== Krasilnikov-Ilya/XmlJson_Practice/_Примеры/Володя (крутой дофига)/Homework.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="document">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="document_type" type="xs:string"/>
					<xs:element name="main_page">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="series">
									<xs:simpleType>
										<xs:restriction base="xs:integer">
											<xs:pattern value="\d{4}"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="number">
									<xs:simpleType>
										<xs:restriction base="xs:integer">
											<xs:pattern value="\d{6}"/>
										</xs:restriction>
									</xs:simpleType>	
								</xs:element>
								<xs:element name="first_name" type="xs:string"/>
								<xs:element name="last_name" type="xs:string"/>
								<xs:element name="patronomyc" type="xs:string"/>
								<xs:element name="dob" type="date_format"/>
								<xs:element name="gender">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="МУЖ"/>
											<xs:enumeration value="ЖЕН"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="date_of_issue" type="date_format"/>
								<xs:element name="place_of_issue" type="xs:string"/>
								<xs:element name="division_code">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:pattern value="\d{3}-\d{3}"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
				</xs:element>
				<xs:element name="registration">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="date_of_registraion" type="date_format"/>
							<xs:element name="city" type="xs:string"/>
							<xs:element name="region" type="xs:string" minOccurs="0"/>
							<xs:element name="district" type="xs:string" minOccurs="0"/>
							<xs:element name="street" type="xs:string" minOccurs="0"/>
							<xs:element name="house" type="xs:positiveInteger"/>
							<xs:element name="building" type="xs:positiveInteger" minOccurs="0"/>
							<xs:element name="flat_number" type="xs:positiveInteger" minOccurs="0"/>

						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="date_format">
       <xs:restriction base="xs:string">
           <xs:pattern value="\d{2}[.]\d{2}[.]\d{4}"/>
            <xs:length value="10"/>
        </xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Krasilnikov-Ilya/XmlJson_Practice/_Примеры/Володя (крутой дофига)/Homework.xml
<?xml version="1.0" encoding="utf-8"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="Homework.xsd">
  <document_type>Паспорт РФ</document_type>
  <main_page>
    <series>130</series>
    <number>145676</number>
    <first_name>Василий</first_name>
    <last_name>Пупкин</last_name>
    <patronomyc>Леонтьевич</patronomyc>
    <dob>08.08.1990</dob>
    <gender>МУЖ</gender>
    <date_of_issue>12.12.2000</date_of_issue>
    <place_of_issue>ТП2 ОУФМС РОССИИ по г. Москве</place_of_issue>
    <division_code>500-100</division_code>
  </main_page>
  <registration>
    <date_of_registraion>13.02.1993</date_of_registraion>
    <city>Москва</city>
    <district>Московская</district>
    <street>Молостовых</street>
    <house>8</house>
    <building>3</building>
    <flat_number>745</flat_number>
  </registration>
</document>
